gateway:
  address: "127.0.0.1:50051"

serial:
  port: "/dev/robot_display"
  baudrate: 256000

display:
  selected_ids:
    - id: "cpu"
    - id: "voltage"
      scale: 10
    - id: "hz_driver"
    - id: "hz_slam"

reconnect_delay_s: 2.0
